-- Add the eight browser-only tools to the existing admin catalog.
insert into public.tools (id,slug,name,category,description,status) values ('url-encoder-decoder','url-encoder-decoder','URL Encoder & Decoder','Developer tools','Encode or decode URL components and complete URLs.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('jwt-decoder','jwt-decoder','JWT Decoder','Developer tools','Inspect JWT headers, claims, and timestamps locally.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('unix-timestamp-converter','unix-timestamp-converter','Unix Timestamp Converter','Developer tools','Convert Unix seconds or milliseconds to local and UTC dates.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('hash-generator','hash-generator','Hash Generator','Developer tools','Generate SHA-256, SHA-384, and SHA-512 hashes locally.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('csv-to-json','csv-to-json','CSV to JSON Converter','Developer tools','Convert quoted CSV data to JSON without uploading it.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('text-case-converter','text-case-converter','Text Case Converter','Text tools','Convert text between prose and identifier case styles.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('text-diff-checker','text-diff-checker','Text Difference Checker','Text tools','Compare two texts line by line in the browser.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
insert into public.tools (id,slug,name,category,description,status) values ('uuid-generator','uuid-generator','UUID Generator','Generators','Generate cryptographically random RFC 4122 version 4 UUIDs.','active') on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,status=excluded.status;
